sudo: false
language: php

php:
  - 5.6
  - 7.0
  - 7.3
  env:
    TEST=test_7_3
  dist: TEST=test_7_3
  - 7.4snapshot
  env:
    TEST=test_7_4_snapshot
  dist: TEST=test_7_4_snapshot
  - hhvm

allow_failures:
  - php:  7.3
    env: TEST=test_7_3
  - php: 7.4snapshot
    env: TEST=test_7_4_snapshot

install:
  - composer self-update

before_script:
  - composer install --prefer-source -n
